
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-nodeport
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
    tier: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080   # Optional; if omitted, Kubernetes assigns a free port in 30000-32767
``
